### ISSUE TITLE
Incorrect Links on Actions, Resources, and Condition Keys for AWS Resource Access Manager

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/iam-user-guide#101]
In the Actions Defined by AWS Resource Access Manager section, all the links in the table (in the Action column, such as CreateResourceShare or DeleteResourceShare) that are supposed to link to the API actually all redirect here: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/Welcome.html.

This is because all the RAM links have since been moved to a different section.  The old links still point to  https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateResourceShare.html where they should point to https://docs.aws.amazon.com/ram/latest/APIReference/API_CreateResourceShare.html

(ram should be the new high level path directory instead of AWSEC2)

**Comment by stephswo** [comment]
Thanks for finding this! The list of actions, resources, and conditions that we publish in the IAM user guide is automated based on content from each service. Thanks for letting us know that this service includes incorrect or out of date data. I will forward this information to the service's engineering team so that they can add the missing information.
