### ISSUE TITLE
Missing IAM Action states:TagResource in Step Functions

### ISSUE THREAD

**Issue by sriramho** [awsdocs/iam-user-guide#102]
Missing IAM Action states:TagResource in the documentation https://docs.aws.amazon.com/IAM/latest/UserGuide/list_awsstepfunctions.html. 

StepFunctions started to support resource tagging from Jan 7th 2019 as per the documentation https://docs.aws.amazon.com/step-functions/latest/dg/document-history.html 
However the IAM permission document is not updated with the recent updates and changes to StepFunction permissions. 

Please update the documentation so that users are aware about the new IAM Action available for StepFunctions

**Comment by stephswo** [comment]
The list of actions, resources, and conditions that we publish in the IAM user guide is automated based on content from each service. Thanks for letting us know that this service includes information that is not known to IAM. I will forward this information to the service's engineering team so that they can add the missing information.
