### ISSUE TITLE
S3 Condition keys documents has redundant and missing information

### ISSUE THREAD

**Issue by bksarthak** [awsdocs/iam-user-guide#103]
S3 Condition keys page has multiple missing descriptions in the key table towards end of the page.

Also, s3:locationconstraint has two entries, one all lowercase and one camel-case. I don't think there is a difference between both entries.

**Comment by stephswo** [comment]
The list of actions, resources, and conditions that we publish in the IAM user guide is automated based on content from each service. Thanks for letting us know that this service includes invalid data or information that is not known to IAM. I will forward this information to the service's engineering team so that they can add the missing information.
