### ISSUE TITLE
Document aws:PrincipalArn

### ISSUE THREAD

**Issue by copumpkin** [awsdocs/iam-user-guide#110]
It was mentioned/announced in the new SCP release but not fully specified and I don't think it's made it into the documentation yet.

Here are questions that come to mind as a user:

1. I know why it's desirable over the `Principal` element but it's probably not obvious to folks when they might want one vs. the other (cover the counterintuitive behavior of `Deny` on `NotPrincipal` and such)
2. How does `aws:PrincipalArn` behave on non-AWS principals? I'm talking principals from the `Service` namespace, `Federated` namespace, and so on. Is it unset? Set but unspecified? Should we assume it's always set when `aws:userid` is set?

The existing minimal documentation at https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html just mentions very briefly that it's a condition key and works with string operators (doesn't mention ARN operators, which I think are a better fit for it and still work) and doesn't cover any of the deeper semantics.

**Comment by stephswo** [comment]
You're right about the string type vs. ARN data type. I updated that and the changes will be live later today. 

I'm checking with folks on the team about your other questions so that I can add more details to the condition key docs.

**Comment by copumpkin** [comment]
Thanks! Also very happy that the condition key now exists, in case the team needed some positive reinforcement 😄

**Comment by lpiedade** [comment]
Considering the SCP is useful to "Deny" actions, SCP could support NotPrincipal to whitelist some AWS Services (not give a permission).

**Comment by ljquin** [comment]
@copumpkin - We've made updates to IAM documentation since this issue was created.

For question 1, additional details were added covering when you may want to use condition key `aws:PrincipalArn` instead of the Principal policy element, see links [1] and [2]. Updates were also made to the **NotPrincipal With Deny** topic clarifying policy evaluation behavior when using this policy configuration, see link [3].

For question 2, updates were made to the `aws:PrincipalArn` condition key reference topic, see link [4]. This topic details the different types of principals that can be specified in the `aws:PrincipalArn` condition key and includes ARN examples. If the calling principal is one of the supported principal types this key will be present. Anonymous requests do not include this key.

Referenced Links:
[1] AWS JSON policy elements: Principal - IAM role principals - https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html#principal-roles
[2] AWS JSON policy elements: Principal - Role session principals - https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html#principal-role-session
[3] AWS JSON policy elements: NotPrincipal - NotPrincipal With Deny - https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_notprincipal.html#specifying-notprincipal
[4] AWS global condition context keys - aws:PrincipalArn - https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-principalarn

**Comment by ljquin** [comment]
@lpiedade - At this point in time the following elements aren't supported in AWS Organizations service control policies (SCPs):

- Principal
- NotPrincipal
- NotResource

For the latest information on supported elements in AWS Organizations SCPs refer to the following link.

- SCP syntax - https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps_syntax.html

**Comment by ljquin** [comment]
Thanks for taking the time to send us feedback. Please don't hesitate to contact us with any other feedback you might have about our documentation.
