### ISSUE TITLE
AWS Global Condition Keys

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/iam-user-guide#111]
I know SNS has aws:SourceOwner as an available key for SNS.  However, I don’t see this in any AWS documentation (For SNS keys or global keys).  This is in the default SNS access policy applied to topics.

https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#AvailableKeys

**Comment by stephswo** [comment]
Thanks! I wasn't aware of this one. I'll look into it.

**Comment by tamakisquare** [comment]
@stephswo Any plan to add a formal definition for `aws:SourceOwner` to the documentation?

**Comment by stephswo** [comment]
I’ll check with the service team and see if that’s something the team wants to publish.

Stephenie Swope
Senior Technical Writer and Manager, AWS Identity

**Comment by ecerulm** [comment]
@stephswo , still `aws:SourceOwner` is not documented at https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#AvailableKeys, has it been decided that it's not going to be documented there?  If so ,then maybe it would be good to say so here and close the issue.

**Comment by bonniekeller** [comment]
Thanks so much for the contributions. We don't plan to document aws:SourceOwner. [aws:SourceAccount](https://github.com/awsdocs/iam-user-guide/blob/main/doc_source/reference_policies_condition-keys.md#awssourceaccount) was introduced as the preferred replacement.

**Comment by iugrina** [comment]
@bonniekeller The default policy created by AWS when creating a new topic through the Web Console includes "AWS:SourceOwner" so I'm not sure if you need to change that since "[aws:SourceAccount](https://github.com/awsdocs/iam-user-guide/blob/main/doc_source/reference_policies_condition-keys.md#awssourceaccount) was introduced as the preferred replacement.". IMHO this is a bit suboptimal for those trying to understand access policies for topics :(

**Comment by bonniekeller** [comment]
@iugrina I've passed your feedback along to the SNS team. My understanding is that they supported aws:SourceOwner before aws;SourceAccount was introduced.
