### ISSUE TITLE
Unclear information on ram:AllowsExternalPrincipals

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/iam-user-guide#114]
The Condition key here for ram:AllowsExternalPrincipals states that resource shares can only be acted on if the share allows external principals, but isn't clear on what is an external principal.

From this page, https://docs.aws.amazon.com/ram/latest/userguide/control-access.html I can infer that external principals are AWS accounts that are outside of its AWS organization.

Would be good to be clear on this page for condition keys.

**Comment by stephswo** [comment]
The list of actions, resources, and conditions that we publish in the IAM user guide is automated based on content from each service. Thanks for letting us know that this service includes information that is not known to IAM. I will forward this information to the service's engineering team so that they can update the information.
