### ISSUE TITLE
Document inconsistent with AWS Glue API reference

### ISSUE THREAD

**Issue by j2clerck** [awsdocs/iam-user-guide#115]
Hello,

I have noticed a lot of discrepencies between IAM and Glue actions reference.

Example: BatchStopJobRun is not reference in IAM documentation regarding Glue but it is referenced in Glue API reference.
Although a lot of details are missing for condtions and resource in the IAM documentation.

https://docs.aws.amazon.com/glue/latest/dg/api-permissions-reference.html

Regards,
Joseph de Clerck

**Comment by stephswo** [comment]
I'm sorry that you're having trouble finding the information you need. The list of actions, resources, and conditions that we publish in the IAM user guide is automated based on content from each service. Thanks for letting us know that this service includes information that is not known to IAM. I will forward this information to the service's engineering team so that they can add the missing information.
