### ISSUE TITLE
Incorrect link for ListTags

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/iam-user-guide#126]
ListTags on this page https://docs.aws.amazon.com/IAM/latest/UserGuide/list_awslambda.html goes to a broken link (https://docs.aws.amazon.com/lambda/latest/dg/API_ListTagsForResource.html).  This should direct to https://docs.aws.amazon.com/lambda/latest/dg/API_ListTags.html

**Comment by nicholaspierson** [comment]
Thank you for your contribution. The IAM writer is out of the office until the end of June. She will address this when she returns.

**Comment by stephswo** [comment]
Thanks! 
I'm sorry that you're having trouble finding the information you need. The list of actions, resources, and conditions that we publish in the IAM user guide is automated based on content from each service. Thanks for letting us know that this service includes incorrect information. I will forward this information to the service's engineering team so that they can update the broken link.
