### ISSUE TITLE
Missing ResourceTag for CloudFormation Condition Keys 

### ISSUE THREAD

**Issue by n-scozzafava** [awsdocs/iam-user-guide#127]
## Issue Description
As of May 30, 2019, CloudFormation introduced support for [Tag-Based Access Control](https://aws.amazon.com/about-aws/whats-new/2019/05/announcing-tag-based-access-control-for-aws-cloudformation/).  The related Tag-Based Access Controls are not included in the respective Conditions section, for example: `cloudformation:ResourceTag/${TagKey} `.  In fact this control is not included in the IAM Policy Generator tool as well, this should be updated to reflect the functionality.  

I was able to use the following condition effectively, despite no support from the GUI or documentation.

```
"Condition": {
        "StringEquals": {
            "cloudformation:ResourceTag/myTagKey": [
                "myTagValue"
            ]
    }
```

## Link to Documentation with Issue
https://github.com/awsdocs/iam-user-guide/blob/master/doc_source/list_awscloudformation.md

**Comment by stephswo** [comment]
Thanks for reporting this. 
The list of actions, resources, and conditions that we publish in the IAM user guide is automated based on content from each service. Thanks for letting us know that this service is missing nformation. I will forward this information to the service's engineering team so that they can update the info.
