### ISSUE TITLE
Broken link for Instance Connect, Learning how to protect by using IAM permission

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/iam-user-guide#133]
The link here: Learn how to protect this service and its resources by using IAM permission policies directs to this page: https://docs.aws.amazon.com/IAM/latest/UserGuide/$%7BUserDocRoot%7DUserGuide/ec2-instance-connect-set-up.html (which is broken).

I believe this should direct to this page:

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-set-up.html#ec2-instance-connect-configure-IAM-role

**Comment by stephswo** [comment]
Thanks for reporting this. The list of actions, resources, and conditions that we publish in the IAM user guide is automated based on content from each service. Thanks for letting us know that this service includes incorrect information. I will forward this information to the service's engineering team so that they can update the info.
