### ISSUE TITLE
Missing ecs:SubmitAttachmentStateChanges in action list for ECS

### ISSUE THREAD

**Issue by fcoelho** [awsdocs/iam-user-guide#137]
The IAM page for ECS actions already include some ECS agent-only actions (such as [`SubmitTaskStateChange`](https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazonelasticcontainerservice.html#amazonelasticcontainerservice-SubmitTaskStateChange)) but [`SubmitAttachmentStateChanges`](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_SubmitAttachmentStateChanges.html) is missing from there

**Comment by stephswo** [comment]
I'm sorry that you're having trouble finding the information you need. The list of actions, resources, and conditions that we publish in the IAM user guide is automated based on content from each service. Thanks for letting us know that this service includes incorrect information. I will forward this information to the service's engineering team so that they can update the info.
