### ISSUE TITLE
Tag Enforcement

### ISSUE THREAD

**Issue by AjithKumar-Raj** [awsdocs/iam-user-guide#172]
Need a any tag values enforcement example - https://aws.amazon.com/premiumsupport/knowledge-center/iam-policy-tags-restrict/

Create a policy for multi keys and value enforcement like bellow

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "ec2:RunInstances",
                "ec2:CreateVolume"
            ],
            "Resource": [
                "arn:aws:ec2:*:*:instance/*",
                "arn:aws:ec2:*:*:volume/*"
            ],
            "Condition": {
                "Null": {
                    "aws:RequestTag/tag1": "false",
                    "aws:RequestTag/tag2": "false",
                    "aws:RequestTag/tag3": "false",
                    "aws:RequestTag/tag4": "false"
                },
                "ForAllValues:StringEquals": {
                    "aws:TagKeys": [
                        "tag1",
                        "tag2",
                        "tag3",
                        "tag4"
                    ]
                },
                "StringNotEquals": {
                    "aws:RequestTag/tag1": [
                        ""
                    ],
                    "aws:RequestTag/tag2": [
                        ""
                    ],
                    "aws:RequestTag/tag3": [
                        ""
                    ],
                    "aws:RequestTag/tag4": [
                        ""
                    ]
                }
            }
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "ec2:CreateTags",
            "Resource": [
                "arn:aws:ec2:*:*:instance/*",
                "arn:aws:ec2:*:*:volume/*"
            ],
            "Condition": {
                "StringEquals": {
                    "ec2:CreateAction": "RunInstances"
                }
            }
        },
        {
            "Sid": "VisualEditor2",
            "Effect": "Allow",
            "Action": "ec2:Describe*",
            "Resource": "*"
        },
        {
            "Sid": "VisualEditor3",
            "Effect": "Allow",
            "Action": "ec2:RunInstances",
            "Resource": [
                "arn:aws:ec2:*:*:subnet/*",
                "arn:aws:ec2:*:*:key-pair/*",
                "arn:aws:ec2:*::snapshot/*",
                "arn:aws:ec2:*:*:security-group/*",
                "arn:aws:ec2:*:*:network-interface/*",
                "arn:aws:ec2:*::image/*"
            ]
        }
    ]
}
```

This policy was override by PowerUserAccess policy following

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "NotAction": [
                "iam:*",
                "organizations:*",
                "account:*"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "iam:CreateServiceLinkedRole",
                "iam:DeleteServiceLinkedRole",
                "iam:ListRoles",
                "organizations:DescribeOrganization",
                "account:ListRegions"
            ],
            "Resource": "*"
        }
    ]
}
```

Please attach example for this case

**Comment by bonniekeller** [comment]
Hi,

Your first policy is similar to the ones on this page in the documentation: https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_attribute-based-access-control.html

The policy is correct, and allows actions only under specific conditions – when tags are present. As with any policy, if you apply a different policy to your users or roles that has broader permissions, then this policy won’t limit the effective permissions to ONLY use tags. For example, if your user is allowed the PowerUserAccess permissions, they are a power user and you can’t limit their broad permissions without using “Deny” statements. For more information about how permissions are determined when multiple policies are involved, see https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_evaluation-logic.html#policy-eval-denyallow.

I think that you’re asking for a policy that denies access EXCEPT when the specified tags are present. You do this using “Deny” and “NotAction”. For an example of this, see https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_aws_my-sec-creds-self-manage.html. 

We don’t have a published policy for this and don’t really recommend it. The reason is that if you use policies with “Deny” statements, then other “Allow” statements added in the future won’t take effect. This can be problematic. A deny always overrides an allow. Additionally, the “PowerUserAccess” is a broad, nearly full-access policy. Instead, we recommend that you allow only the actions that the user needs to do their job. For more information, see To see an example of this, view https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html#grant-least-privilege.

If you’re looking for an easy policy that allows access to all of the services only the user applies tags, then it doesn’t exist. Each service implemented tags differently and their policies must be different. If you need help crafting custom policies and if you have purchased a support package or need help with account management, you can contact support at https://aws.amazon.com/support/. Alternatively, you can crowdsource your information or search for similar issues in our forums: https://forums.aws.amazon.com/index.jspa.

**Comment by AjithKumar-Raj** [comment]
Thanks @bonniekeller for your information.
