### ISSUE TITLE
Question: Role of "[permission only]" in Action section?

### ISSUE THREAD

**Issue by jjshoe** [awsdocs/iam-user-guide#182]
https://github.com/awsdocs/iam-user-guide/blob/master/doc_source/list_amazoncodegurureviewer.md

What role does listing `[permission only]` serve in the action cell?

**Comment by bonniekeller** [comment]
Hi, thanks for the question. PermissionOnly indicates that you can grant permission to the action in a policy, but there is not a corresponding API associated to it. There are a couple of reasons for PermissionOnly actions. Some services are console-only and do not have an API. CodeGuru Reviewer does have an API, but not all of the console actions directly correspond with an API operation. Another example is iam:PassRole. Because roles grant permissions, a user must have permissions for iam:PassRole in order to pass (or grant access to) the role for an AWS service to use, but there is not a PassRole API operation.
