### ISSUE TITLE
Seems not possible to change IAM Object Limits

### ISSUE THREAD

**Issue by hktonylee** [awsdocs/iam-user-guide#190]
In this [document](https://github.com/awsdocs/iam-user-guide/blob/master/doc_source/reference_iam-limits.md#user-content-iam-object-limits) it mentions that we can change object limits of IAM. But if you follow the steps in the "AWS Service Limits", there is no way you change the object limits of IAM. Because the Service Quotas does not contain IAM at all. Please review this part and update the text correspondingly.

**Comment by bonniekeller** [comment]
You can request changes for the IAM limits via the AWS Support Center. I'm sorry, IAM is not yet available in Servcie Quotas. See the last bullet in the section, [**To request a quota increase**](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) in the AWS General Reference documentation. This is the page we link to from the[ IAM limits ](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-limits.html) page.

**Comment by bonniekeller** [comment]
I have to apologize because I gave you bad information. You can request limit changes using Service Quotas. From the Service Quotas console, make sure that you have selected the us-east-1/N.Virginia region, then search for AWS Identity and Access Management in the AWS services search bar. If you don't have us-east-1 selected, IAM won't appear in the list.
