### ISSUE TITLE
Broken links in 10 services

### ISSUE THREAD

**Issue by udondan** [awsdocs/iam-user-guide#213]
On 10 service descriptions I found broken links. Either the links only contain the HTML document without any path or they contain unresolved placeholders.

No, I did not manually check all links in the docs. 😼 This is discovered when generating code from the docs for [iam-floyd](https://github.com/udondan/iam-floyd). Here is an [example CI build](https://github.com/udondan/iam-floyd/runs/1078761144?check_suite_focus=true#step:4:288).

amazonchime:
- API_BatchCreateRoomMembership.html
- API_CreateBot.html
- API_CreateBotMembership.html
- API_CreateRoom.html
- API_CreateRoomMembership.html
- API_DeleteEventsConfiguration.html
- API_DeleteRoom.html
- API_DeleteRoomMembership.html
- API_GetBot.html
- API_GetEventsConfiguration.html
- API_GetRetentionSettings.html
- API_GetRoom.html
- API_ListBots.html
- API_ListRoomMemberships.html
- API_ListRooms.html
- API_PutEventsConfiguration.html
- API_PutRetentionSettings.html
- API_RedactConversationMessage.html
- API_RedactRoomMessage.html
- API_RegenerateSecurityToken.html
- API_UpdateBot.html
- API_UpdateRoom.html
- API_UpdateRoomMembership.html

amazonelasticache:
- AmazonElastiCache/latest/red-ug/WhatIs.Components.html
- AmazonElastiCache/latest/red-ug/WhatIs.Components.html
- AmazonElastiCache/latest/red-ug/WhatIs.Components.html
- AmazonElastiCache/latest/red-ug/Replication.html
- AmazonElastiCache/latest/red-ug/WhatIs.Components.html
- AmazonElastiCache/latest/red-ug/reserved-nodes.html
- AmazonElastiCache/latest/red-ug/backups.html
- AmazonElastiCache/latest/red-ug/Redis-Global-Datastore.html

amazonelasticfilesystem:
- efs-access-points.html

amazonrds:
- {ActionsDocRoot}API_DBClusterEndpoint.html

amazonredshift:
- API_DeleteScheduledAction.html
- API_DescribeScheduledActions.html

amazons3:
- {ConceptsDocRoot}replication-config-for-kms-objects.html
- {ConceptsDocRoot}setting-repl-config-perm-overview.html

awsbatch:
- ${AuthZDocPage}compute_environments.html
- ${AuthZDocPage}job_queues.html
- ${AuthZDocPage}job_definitions.html

awscloudformation:
- ${DocumenationLink}using-iam-template.html#using-iam-template-conditions
- ${DocumenationLink}using-iam-template.html#using-iam-template-conditions
- ${DocumenationLink}using-iam-template.html#using-iam-template-conditions
- ${DocumenationLink}using-iam-template.html#using-iam-template-conditions
- ${DocumenationLink}using-iam-template.html#using-iam-template-conditions
- ${DocumenationLink}using-iam-template.html#using-iam-template-conditions
- ${DocumenationLink}using-iam-template.html#using-iam-template-conditions
- ${DocumenationLink}using-iam-template.html#using-iam-template-conditions
- ${DocumenationLink}using-iam-template.html#using-iam-template-conditions

awscodestarconnections:
- ${AuthZDocPage}#connections-permissions-actions-handshake
- ${AuthZDocPage}#connections-permissions-actions-handshake
- ${AuthZDocPage}#connections-permissions-actions-handshake
- ${AuthZDocPage}#connections-passconnection
- ${AuthZDocPage}#connections-permissions-actions-handshake
- ${AuthZDocPage}#connections-permissions-actions-handshake
- ${AuthZDocPage}#connections-use

awsiot:
- API_TagResource.html
- API_UntagResource.html
- API_UpdateAuthorizer.html
- API_UpdateDimension.html
- API_UpdateMitigationAction.html
- API_UpdateProvisioningTemplate.html
- API_UpdateRoleAlias.html
- API_UpdateScheduledAudit.html
- API_UpdateSecurityProfile.html
- API_ValidateSecurityProfileBehaviors.html

**Comment by bonniekeller** [comment]
Thank you so much for taking the time to compile all of these broken links. I’m sorry for the slow response. The list of actions, resources, and conditions that we publish in the IAM user guide is automated based on content from each service. I’ve either noted existing tickets that are already open with new the feedback you provided, or I have created new tickets with the information you reported and sent them to each of the service's engineering teams so that they can update the info. Unfortunately, because the way that we automate the information on these pages comes from each of 230+ services that all integrate with IAM, we IAM writers are unable to make necessary changes to the pages on GitHub. I apologize because I know this might be an inconvenience for you, but it’s a limitation of the way that our documentation is created. 

In the future, you can leave feedback on the HTML version of these pages by finding the service in the list here: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_actions-resources-contextkeys.html. You can choose the Feedback option at the top right of the page. When you leave feedback, a ticket is automatically sent to us and we route it to the relevant service team.
