### ISSUE TITLE
Help Wanted – Troubleshooting Tips, Tricks, and Strategies

### ISSUE THREAD

**Issue by carlasp** [awsdocs/iam-user-guide#26]
As you know, troubleshooting problems with IAM and its many moving parts can be a challenge. What issues have you run into and solved? Can you share your solution with your peers? Please share only problems for which you've found a solution. If you're still struggling with a problem, please contact Customer Support or post your issue on the AWS Forums.

Share the following information with the IAM doc team as a response to this issue, and we'll consider adding it to the troubleshooting section of the AWS IAM documentation.

- What were the symptoms of the problem?
- What did you do to troubleshoot? 
- What did you try that didn't help? 
- What led you to the correct root cause?
- What did you do to correct the problem?

On behalf of all of your colleagues who run into the same problems, we thank you for your participation.

Stephenie Swope
Senior Technical Writer
AWS Identity and Access Management

Carla Spoon 
Technical Writer
AWS Identity and Access Management and AWS Organizations

https://docs.aws.amazon.com/iam/latest/userguide/

**Comment by 0xdabbad00** [comment]
As a consultant brought in to assess the security posture of an AWS account, I wanted to identify who all in an account is admin.  I built the `find_admins` command into the open-source CloudMapper to do this.  Explanation at https://summitroute.com/blog/2018/06/12/cloudmapper_find_admins/

In order to help companies with their least privileges, I built the open-source CloudTracker.  See https://duo.com/blog/introducing-cloudtracker-an-aws-cloudtrail-log-analyzer

When trying to identify the least privileges for a new service, the common solution is to provide more privileges than are needed, and then to review CloudTrail logs to identify the actual privileges needed.  This is partially because there are naming differences between API names -> IAM privilege names -> CloudTrail names, which makes figuring out the IAM privileges difficult.  For example the IAM service `SES` is recorded in CloudTrail as `email`.  Or the IAM privilege `s3:listallmybuckets` is recorded in CloudTrail as 's3:listbuckets'.  Some API calls are also not recorded in CloudTrail, making this approach difficult. These issues have been recorded as open issues to the CloudTrail team at https://github.com/awsdocs/aws-cloudtrail-user-guide/issues/2 and https://github.com/awsdocs/aws-cloudtrail-user-guide/issues/1

**Comment by MaxEliaserAWS** [comment]
This is a pretty rookie issue but it might help someone anyway.

I had an issue that looked like I had either misconfigured my role's permissions, or I wasn't using the role correctly in my application (C++ SDK.) I was getting "access denied" on an attempted S3 upload. I had an Aws::Auth::AWSCredentials and I could get the key and secret key from that, but there was no obvious way to associate that information with the actual name of the role or query what permissions it had.

I spent a lot of time staring at my C++ code, the source code for the AWS C++ SDK, and my IAM policies. I also tried setting the AWS_ACCESS_KEY and AWS_SECRET_ACCESS_KEY environment variables to the values from my Aws::Auth::AWSCredentials and then running AWS CLI S3 commands, but I wasn't able to learn anything that way either.

It turns out that the right way to figure out what role I was actually getting credentials for was to look in CloudTrail. I quickly realized that I was using the wrong IAM _user_, because I was able to associate the access key from my AWSCredentials with an actual user name. So it would be helpful if the "Troubleshooting IAM" section of the user guide would mention CloudTrail somewhere, since that seems like a helpful way to see what your code is actually trying to do with IAM.

**Comment by 0xdabbad00** [comment]
I described the more confusing aspects of IAM's naming and how it relates to the API names and CloudTrail here: https://summitroute.com/blog/2018/06/28/aws_iam_vs_api_vs_cloudtrail/

**Comment by 0xdabbad00** [comment]
@MaxEliaserAWS for your issue, `aws sts get-caller-identity` is one of the most important API calls that exists.  Not only will it tell you what user/role you are using for your credentials, but it is also one of the few API calls that cannot be denied, so it always works as long as the credentials are valid, no matter what IAM privileges have been denied or allowed.

**Comment by carlasp** [comment]
Thank you, @0xdabbad00. @MaxEliaserAWS, @0xdabbad00 is correct that get-caller-identity would be helpful in your situation. For more information, see the documentation here: https://docs.aws.amazon.com/cli/latest/reference/sts/get-caller-identity.html.

Also, I have logged your request for adding CloudTrail info to IAM troubleshooting. Good idea! Thanks for your feedback.

**Comment by bonniekeller** [comment]
We're working to close older GitHub issues for the IAM User Guide, and we appreciate the suggestions that were made here previously. We added section to the IAM troubleshooting section to mention Cloud Trail: https://github.com/awsdocs/iam-user-guide/blob/main/doc_source/troubleshoot_general.md#additional-resources.
