### ISSUE TITLE
Confusing example on aws:MultiFactorAuthPresent

### ISSUE THREAD

**Issue by joelthompson** [awsdocs/iam-user-guide#28]
The following text in [doc_source/reference_policies_condition-keys.md](https://github.com/awsdocs/iam-user-guide/blob/fda32b622ed2c7950e7e7c539d6576180ba21d1d/doc_source/reference_policies_condition-keys.md) has always confused me:

> Do not use a policy construct similar to the following to check whether the MFA key is present:
> 
> ```
> #####     THIS EXAMPLE DOES NOT WORK      #####
> 
> "Action" : "Deny",
> "Condition" : { "Null" : { "aws:MultiFactorAuthPresent" : true } }
> ```
> You might expect the previous example to deny access if MFA is not used. However, when you make an API request with long-term credentials (access keys), the MFA condition context keys are always missing. Consequently, testing for MFA this way always results in denied access to long-term credentials.

Doesn't the last sentence of "testing for MFA this way always results in denied access to long-term credentials" confirm that the example does in fact "deny access if MFA is not used" and thus the thing that we might expect is in fact an accurate expectation? And thus, isn't the example a perfectly reasonable and valid way to deny all access unless MFA auth is used? It has been a few years since I've tested, but I seem to recall that it worked exactly as I expected.

**Comment by carlasp** [comment]
Thanks for your post! 

The problem is described in detail in the first paragraph of this section:
==
This key is present in the request context only when the user uses temporary credentials to call the API. Such credentials are used with IAM roles, federated users, IAM users with credentials from sts:GetSessionToken, and users of the AWS Management Console. (The console uses temporary credentials that are generated on the users' behalf in the background.) The aws:MultiFactorAuthPresent key is never present when an API or CLI command is called with long-term credentials, such as standard access key pairs. Therefore we recommend that when you check for this key that you use the ...IfExists versions of the condition operators. 
==
In the section that you pointed out, we are reiterating the fact that if you don’t use the IfExists version of the condition operator, then any IAM users that make API requests will be denied access, whether or not they are authenticated using MFA. The expectation would be that users with MFA would NOT be denied access, and that is not true. 

I am making some edits to the paragraph you mentioned to make this more clear there. 

Thanks again for your post!

**Comment by joelthompson** [comment]
Thanks @carlasp for the response, but I'm still confused.

As far as I'm aware, the ONLY way for IAM users to be authenticated with MFA is to call sts:GetSessionToken, signed with the IAM user's long-term credentials, and passing in the SerialNumber and TokenCode parameters. The resulting credentials are temporary credentials and will have the aws:MultiAuthFactorPresent key present. Thus, the policy snippet in question would NOT deny access to the credentials returned from GetSessionToken when they are MFA authenticated, but it will deny access to long-term credentials which are, by definition, NOT MFA-authenticated because they're long-term credentials.

Am I missing something here? Is there a way for long-term credentials to be MFA authenticated?
