### ISSUE TITLE
Inconsistent naming for Amazon/AWS services

### ISSUE THREAD

**Issue by copumpkin** [awsdocs/iam-user-guide#38]
I was scanning [this list](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_actions-resources-contextkeys.html) and noticed that the naming for all the individual services is pretty inconsistent. I've also noticed this elsewhere in the AWS IAM world (like the online policy editor, which has the same names):

Contrast the following:

* Amazon Elasticsearch Service
* Amazon ElastiCache
* AWS Key Management Service
* Identity And Access Management
* Amazon API Gateway
* Manage Amazon API Gateway

Basically, inconsistency between whether the service is called "AWS" or "Amazon" (or neither, in the case of IAM or SSO), and sometimes a seemingly redundant "service" is added to the end of the name. The "Manage Amazon API Gateway" one is weird too.

Luckily it seems like the list is alphabetized by the important bit, but the inconsistent prefix (lengths vary) makes it very hard to visually scan the list looking for something.

I assume these names reflect some sort of internal organizational details but it's confusing for users and I was wondering if something could be done to improve consistency in the IAM documentation at least.

**Comment by carlasp** [comment]
Thank you for your comment, copumpkin. We understand your issue with the naming inconsistencies, which is why we made sure the list is alphabetized as is now. Making changes to the service names is outside of the scope of IAM documentation. We cannot present the list any other way but to use the actual service names. We appreciate your feedback!

**Comment by joelthompson** [comment]
Hi @carlasp -- could the documentation at least be consistent with the use of acronyms vs. full names? For example, the page lists "Amazon EC2" instead of "Amazon Elastic Compute Cloud" (or it could even be, "Amazon Elastic Compute Cloud (EC2)") and "Amazon S3" instead of "Amazon Simple Storage Service." However, it has "Identity and Access Management" versus "IAM" and "AWS Key Management Service" instead of "AWS KMS." It's frustrating not knowing whether to search for the full name or the acronym.
