### ISSUE TITLE
Confusing Description for StringLikeIfExists

### ISSUE THREAD

**Issue by megachromemonkey** [awsdocs/iam-user-guide#58]
There's a particular sentence in Section [...IfExists Condition Operators](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_IfExists) of the  [IAM JSON Policy Elements: Condition Operators](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html) documentation that's I'm having a hard time wrapping my head around.

> If the policy key is present in the context of the request, process the key as specified in the policy. **If the key is not present, evaluate the condition element as true.**

Applying this statement to the below bucket policy, I interrupt this to mean
1. All s3:PutObject requests from accounts (including master) within the organization 'foo' are explicitly **DENIED**. The EC2 service is **ALLOWED** to use s3:PutObject.

2. If the key (Organization ID = foo) is not present the condition is **TRUE**, so IAM will explicitly **DENY** all AWS accounts.  Including internal accounts associated with a service principal name.

```
{
	"Version": "2012-10-17",
	"Statement": [{
			"Principal": "*",
			"Effect": "Deny",
			"Action": "s3:PutObject",
			"Resource": "*",
			"Condition": {
				"StringLikeIfExists": {
					"aws:PrincipalOrgID": "foo"
				}
			}
		},
		{
			"Principal": {"Service": "ec2.amazonaws.com"},
			"Effect": "Allow",
			"Action": "s3:PutObject",
			"Resource": "*"
		}
	]
}
```

**Comment by stephswo** [comment]
I'm not very knowedgeable about Organization IDs. I'll ask the Orgs writer to chime in. But as far as the mechanics of this policy, here's what the statements say:

**Statement 1:** Deny access to PutObject requests for every account in AWS with a principal Org ID of "foo", and deny access to PutObject requests for every account in AWS that does not have a principal Org ID passed in the request. 

**Note** - This does not deny access to every account in AWS that has a different Principal Org ID. So if my account has a PrincipalOrgID of "bar", then access is not explicitly denied.

**Statement 2:** Allow the PutObject request when the EC2 service in the same account (not organization) makes the call.

**Scenarios:** Assume that the S3 bucket `abc123` in account `111111111111` has the bucket policy above. Let's consider the following scenario:
1. Account `222222222222` is in the `foo` organization. The EC2 service in that account makes a call to put an object in the `abc123` S3 bucket in account `111111111111`. The request is **explicitly denied** because statement 1 denies it.
1. Account `333333333333` is in the `bar` organization. The EC2 service in that account makes a call to put an object in the `abc123` S3 bucket in account `111111111111`. The request is **allowed** because statement 1 does not deny it and statement 2 allows it. In statement 1, the condition evaluates to false because the key is present, but the key value is "bar" and not "foo". Therefore the **Deny** does not apply. 
1. Account `444444444444` is in the `bar` organization. An IAM user in that account makes a call to put an object in the `abc123` S3 bucket in account `111111111111`. The request is **implicitly denied** because statement 1 does not deny it, and statement 2 does not allow it.
1. Account `555555555555` is a standalone account that is not a member of an organization. The EC2 service in that account makes a call to put an object in the `abc123` S3 bucket in account `111111111111`. The request is **explicitly denied** because statement 1 denies it. Statement 1 denies it because the key does not exist in the request (since it's not a member of an organization), and therefore the condition evaluates to true.
