### ISSUE TITLE
Missing HeadBucket action

### ISSUE THREAD

**Issue by melusom** [awsdocs/iam-user-guide#65]
Documentation on the `s3:HeadBucket` action is missing from the [IAM documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazons3.html). The [API call itself](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketHEAD.html) is documented.

Credit to @rosswickman for finding the issue.

**Comment by stephswo** [comment]
I'm sorry that you're having trouble finding the information you need. The  list of actions and conditions that we publish in the IAM user guide is automated based on content from each service. Thanks for letting us know that this service includes information that is not known to IAM. I will contact the S3 team so that they can add the missing information.
