### ISSUE TITLE
errors / comments on AWS Amplify IAM docs

### ISSUE THREAD

**Issue by hakanson** [awsdocs/iam-user-guide#86]
Looking at https://docs.aws.amazon.com/IAM/latest/UserGuide/list_awsamplify.html on the web which maps to https://github.com/awsdocs/iam-user-guide/blob/master/doc_source/list_awsamplify.md here, I have some errors / comments:

1. Unclear to me as a new reader what "Aemilia App" is, should this be Amplify App?  Was this an old name?
2. Many links seem to include a extra / (e.g. `https://docs.aws.amazon.com//amplify/latest/user-guide/welcome.html`) which break when clicked
3. Looks like an extra `s` in the domains resource type ARN (e.g. `apps/${AppId}/domainss/${DomainName}` )

**Comment by stephswo** [comment]
Thanks for providing the feedback! We did receive this information in the documentation feedback and here. I'm closing this one as a duplicate. 

For others' information, the list of actions, resources, and conditions that we publish in the IAM user guide is automated based on content from each service. I forwarded this information to the service's engineering team so that theycan fix the broken links and improve the descriptions about Aemilia apps.
