### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by 0xdabbad00** [awsdocs/iam-user-guide#88]
See https://github.com/awsdocs/iam-user-guide/commit/3a0537e1e4fcde8a57525c2e979e34554f7f6666#diff-c67a92ada731432c8bc051338cd661f9R58

Change `/mgmt/mgmt/` back to `/mgmt/` . This is all over the last commit.

**Comment by stephswo** [comment]
Thanks! The list of actions, resources, and conditions that we publish in the IAM user guide is automated based on content from each service. Thanks for letting us know that this service includes invalid links. I will forward this information to the service's engineering team so that they can add the missing information.

**Comment by PatMyron** [comment]
@stephswo still some `mgmt/mgmt` left in this file:

https://github.com/awsdocs/iam-user-guide/blob/0f5432dc0cfd2205a03920743143e9d5d7718aeb/doc_source/list_amazonredshift.md#L32
